### ISSUE TITLE
component-browser module is not defined

### ISSUE THREAD

**Issue by ojedarob** [marko-js-samples/marko-webpack#5]
Webpack is throwing the following error. Any ideas what is causing it ?

Thanks in advance.

ERROR in ./node_modules/marko/components-browser.marko
Module build failed: TypeError: Cannot read property 'module' of undefined
    at Object.module.exports (/Users/ojedarw1/workspace/marko-webpack/node_modules/marko-loader/src/index.js:17:33)
 @ ./src/pages/home/client.js 4:0-27

**Comment by MarcelJoestingmeier** [comment]
Greetings @robojeda 

This is due to a change in Webpack Configuration. I requested to create a pull request for this bug at the marko-loader Repository, but no reaction until today. It is definetely not recommended but you could change it by yourself. Just be careful; reinstalling all node_modules will overwrite the changes.

Go to: /node_modules/marko-loader/src/index.js:17 and change `this.options.module` to `this.rootContext.module`. This solution is not optimal, but unless you want to work with different versions of Webpack, this should work just fine.

Best regards
Marcel Jöstingmeier

**Comment by DylanPiercey** [comment]
Should be fixed in the latest [examples](https://github.com/marko-js/examples).
